# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='app01.Author', verbose_name='\u51fa\u7248\u793e'),
        ),
    ]
